### ISSUE TITLE
Should not fetch the tag of CITA. 

### ISSUE THREAD

**Issue by kaikai1024** [citahub/citahub-docs#107]
We need a new way to show the version docs.

Why shouldn't we to fetch the tag of CITA?
It's not a sync progress. It may show the part of next version, there's a time between with rc and release version, maybe one or two weeks. The new feature of this time merged to develop and merged the the citahub-docs should be on the next version

**Comment by kaikai1024** [comment]
@zhouyun-zoe We'll discuss it later.

**Comment by zhouyun-zoe** [comment]
自动发版的时候去读 rc 的 tag？
#67

**Comment by kaikai1024** [comment]
还是读 **正式版本的 tag**：

* 之后可能不会有冻结的 tag https://github.com/cryptape/cita/blob/develop/release_guide.md
* 文档和代码版本还是要保持一致

这是文档和代码分离的一个问题，我尽量在 CITA 这边控制

**Comment by kaikai1024** [comment]
这边逻辑还是不变好了。

这个可以先关了

**Comment by kaikai1024** [comment]
https://github.com/cryptape/cita/blob/develop/release_guide.md#citahub-docs-%E7%89%88%E6%9C%AC%E6%9B%B4%E6%96%B0
