### ISSUE TITLE
Confuse the two transaction_hash in rpc-guide documentation

### ISSUE THREAD

**Issue by keroro520** [citahub/citahub-docs#110]
Seems we confuse the two transaction_hash in [rpc-guide documentation](https://github.com/cryptape/citahub-docs/blob/master/docs/cita/rpc-guide/rpc.md):

```
0x019abfa50cbb6df5b6dc41eabba47db4e7eb1787a96fd5836820d581287e0236

0xb38e5b6572b2613cab8088f93e6835576209f2b796104779b4a43fa5adc737af
```

e.g. in the [`getTransactionReceipt`](https://github.com/cryptape/citahub-docs/blob/master/docs/cita/rpc-guide/rpc.md#gettransactionreceipt) example, pass params 

`["0x019abfa50cbb6df5b6dc41eabba47db4e7eb1787a96fd5836820d581287e0236"]`, 

but the getting result shows:
 `"transactionHash":"0xb38e5b6572b2613cab8088f93e6835576209f2b796104779b4a43fa5adc737af"`

**Comment by kaikai1024** [comment]
I'll fix that.
