### ISSUE TITLE
Chinese version: emg-brake

### ISSUE THREAD

**Issue by kaikai1024** [citahub/citahub-docs#118]
![Screenshot from 2019-04-01 17-44-37](https://user-images.githubusercontent.com/8768261/55318683-e92eb480-54a5-11e9-81c9-e155b4bc2ed8.png)

**Comment by zhouyun-zoe** [comment]
![image](https://user-images.githubusercontent.com/36949326/55527258-d812bd00-56ca-11e9-80e4-37f9ae8a9baf.png)
done
