### ISSUE TITLE
fix typo and add pictures

### ISSUE THREAD

**Issue by zengbing15** [citahub/citahub-docs#119]
typo: 
![image](https://user-images.githubusercontent.com/40650475/55380017-7bd85d80-5551-11e9-9d10-5be5a4a414ed.png)
add pictures: 
Cyton's download pictures https://docs.citahub.com/en-US/toolchain/cyton/cyton-intro
![image](https://user-images.githubusercontent.com/40650475/55380032-8a267980-5551-11e9-959e-5be5706c537f.png)
![android](https://user-images.githubusercontent.com/40650475/55380066-9f9ba380-5551-11e9-823b-be710b7fd55c.png)
![ios](https://user-images.githubusercontent.com/40650475/55380071-a32f2a80-5551-11e9-8e57-72ea016dfe1e.png)

I remembered I added the pictures in my PR, why was it removed？:thinking_face:

**Comment by zhouyun-zoe** [comment]
#88
