### ISSUE TITLE
Can't build locally

### ISSUE THREAD

**Issue by zengbing15** [citahub/citahub-docs#128]
![image](https://user-images.githubusercontent.com/40650475/55718833-4c34c400-5a2f-11e9-8e93-322c14d605e4.png)

will report an error

![image](https://user-images.githubusercontent.com/40650475/55718967-98800400-5a2f-11e9-8ce1-5f1784078969.png)

**Comment by wuyuyue** [comment]
try rename the siteConfig.js.example to siteConfig.js
add edit it yourself, mainly set algolia "apiKey" and "indexName" yourself local

**Comment by wuyuyue** [comment]
@zengbing15 , detail see #159,  now update the latest and check in your env. if no problem, could close this issue

**Comment by zhouyun-zoe** [comment]
我刚刚pull的最新的代码，`ENABLE_SOURCE_DOCS=true yarn start` 还是报上面的错误
![image](https://user-images.githubusercontent.com/36949326/57285347-9cae4880-70e5-11e9-8239-7f642710b2bc.png)

**Comment by kaikai1024** [comment]
我是去掉 `ENABLE_SOURCE_DOCS=true` 可以

**Comment by zhouyun-zoe** [comment]
`ENABLE_SOURCE_DOCS=true yarn start` 这个应该让build的时候去读 docs 下面的文档。只 `yarn start` 就是去读translate_docs 下面的文档。
@wuyuyue 是否？

**Comment by wuyuyue** [comment]
@zhouyun-zoe @kaikai1024 这个参数是针对docs下面的修改可以看到实际的修改效果，但链接跳转应该是localhost:3000/en/welcome， 当前html里跳转的时候无法去读取这个环境信息，暂时无法去处理；
这个docs只有新起版本的时候CI才会去读取这个目录初始化某个版本的文件夹；目前应该不会去使用，都是各自在某个版本目录下编辑文档吧，
我建议**readme里先隐藏去掉这个参数**; 如果真的要用的话，可以先手动修改website/static/index.html里的地址，或者直接url输入localhost:3000/en/welcome

**Comment by wuyuyue** [comment]
> `ENABLE_SOURCE_DOCS=true yarn start` 这个应该让build的时候去读 docs 下面的文档。只 `yarn start` 就是去读translate_docs 下面的文档。
> @wuyuyue 是否？

是的
