### ISSUE TITLE
Auth of service-config

### ISSUE THREAD

**Issue by kaikai1024** [citahub/citahub-docs#140]
https://docs.citahub.com/zh-CN/next/cita/configuration/service-config#%E6%8E%88%E6%9D%83%E5%90%88%E7%BA%A6%E6%8E%A5%E5%8F%A3

![Screenshot from 2019-04-16 10-19-07](https://user-images.githubusercontent.com/8768261/56177419-21e79580-6031-11e9-87fd-ee68631220d2.png)

**Comment by QingYanL** [comment]
已修复
