### ISSUE TITLE
Add GA

### ISSUE THREAD

**Issue by zhouyun-zoe** [citahub/citahub-docs#145]
Tracking Id：UA-134504127-3
Tracking code：
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-134504127-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-134504127-3');
</script>

**Comment by wuyuyue** [comment]
https://github.com/cryptape/citahub-docs/pull/148
