### ISSUE TITLE
`测试合约` 的链接是错的

### ISSUE THREAD

**Issue by kaikai1024** [citahub/citahub-docs#147]
https://docs.citahub.com/zh-CN/cita/system/auto-exec#%E6%93%8D%E4%BD%9C%E7%A4%BA%E4%BE%8B

`测试合约` 的链接是错的

**Comment by zhouyun-zoe** [comment]
正确的应该是？

**Comment by kaikai1024** [comment]
https://github.com/cryptape/test-contracts/blob/a7b95c771722f8bd4f3db5697b388c06434067f2/AutoExec.sol

**Comment by zhouyun-zoe** [comment]
#153
