### ISSUE TITLE
Problems of v0.22.0

### ISSUE THREAD

**Issue by kaikai1024** [citahub/citahub-docs#156]
1. https://docs.citahub.com/zh-CN/cita/system/node
应该是节点管理

2. https://docs.citahub.com/zh-CN/cita/getting-started#%E9%83%A8%E7%BD%B2cita

这个版本还是用的 `./env.sh` `./daemon.sh`

**Comment by kaikai1024** [comment]
btw, I will ensure the doc(at least getting_start part) is ready for the new version.

**Comment by zhouyun-zoe** [comment]
从哪个版本开始不用 ./env.sh? 0.22.0 是用还是没用？

**Comment by kaikai1024** [comment]
0.22.0 还在用，这是 0.23.0 才改的

**Comment by zhouyun-zoe** [comment]
所以上面第二个小点的问题是指？

**Comment by kaikai1024** [comment]
0.22.0 的文档怎么没有 `./env.sh & ./daemon.sh`
我不知道这是怎么搞的

**Comment by kaikai1024** [comment]
https://github.com/cryptape/citahub-docs/pull/116
