### ISSUE TITLE
保留website/siteConfig.js 

### ISSUE THREAD

**Issue by wuyuyue** [citahub/citahub-docs#159]
CI部署时，脚本替换相关的apikey

好处
1. 对该文件的修改可以生效，目前需要人工介入修改
2. 新项目成员初次构建运行不会出错（需手动修改siteConfig.js.sample文件名并编辑）

潜在问题
本地不要去修改设置真实api-key（仅影响三方搜索服务，其他正常运行）

**Comment by wuyuyue** [comment]
this cause PR #155 not working

**Comment by wuyuyue** [comment]
@jiangxianliang007 @zhouyun-zoe @kaikai1024 @Keith-CY

**Comment by zhouyun-zoe** [comment]
Totally Agree！
