### ISSUE TITLE
现在的目录字体粗细有些问题

### ISSUE THREAD

**Issue by zhouyun-zoe** [citahub/citahub-docs#172]
![image](https://user-images.githubusercontent.com/36949326/56566277-d3179e00-65e4-11e9-861c-ba7a0774e90f.png)
看起来是不一致的。

希望可以这样：
![image](https://user-images.githubusercontent.com/36949326/56566315-eaef2200-65e4-11e9-90c7-7bdc7dd66113.png)

**Comment by wuyuyue** [comment]
#176

**Comment by wuyuyue** [comment]
目录字体设置调整为：
一级 18px
二级 16px
三级 14px
