### ISSUE TITLE
文档搜索出现问题

### ISSUE THREAD

**Issue by zhouyun-zoe** [citahub/citahub-docs#177]
不能搜索了

**Comment by wuyuyue** [comment]
@jiangxianliang007 ,帮查看下服务器上website/siteConfig.js 里algolia的indexName是否正确，目前错误提示
![image](https://user-images.githubusercontent.com/40381396/56716860-eb66f480-676d-11e9-8862-821fcda4f95a.png)

**Comment by wuyuyue** [comment]
无视，应该不是这个问题，本地也是不能搜索

**Comment by wuyuyue** [comment]
搜索已恢复，@zhouyun-zoe
ALGOLIA搜索服务api key出现问题，CY邮件咨询后，回复处理并已恢复

**Comment by QingYanL** [comment]
已修复
