### ISSUE TITLE
The descrition of contract_arguments should **not** use code style

### ISSUE THREAD

**Issue by kaikai1024** [citahub/citahub-docs#178]
[here](https://docs.citahub.com/zh-CN/cita/configuration/chain-config#contract-arguments-%E6%8C%87%E5%AE%9A%E9%93%BE%E8%87%AA%E8%BA%AB%E7%9A%84%E4%B8%80%E4%BA%9B%E7%B3%BB%E7%BB%9F%E9%85%8D%E7%BD%AE%E5%92%8C%E7%B3%BB%E7%BB%9F%E5%90%88%E7%BA%A6%E7%9A%84%E9%85%8D%E7%BD%AE)

![Screenshot from 2019-04-25 17-09-57](https://user-images.githubusercontent.com/8768261/56724246-33414800-677d-11e9-9901-92b6711aa466.png)

**Comment by boundless-forest** [comment]
![选区_048](https://user-images.githubusercontent.com/11801722/56873869-05ebe700-6a68-11e9-8bf4-87fab55110a3.png)

The latest version

**Comment by kaikai1024** [comment]
The desription of next part.

**Comment by boundless-forest** [comment]
> The desription of next part.

I got it

**Comment by kaikai1024** [comment]
preview:

![image](https://user-images.githubusercontent.com/8768261/56880328-d56b7380-6a8e-11e9-8305-b62e0010c3ff.png)
