### ISSUE TITLE
history-doc-version search function failed again

### ISSUE THREAD

**Issue by wuyuyue** [citahub/citahub-docs#203]
version below 0.23 search failed again

![image](https://user-images.githubusercontent.com/40381396/57190178-422cb500-6f4a-11e9-8db2-0a630db40d98.png)

![image](https://user-images.githubusercontent.com/40381396/57190187-540e5800-6f4a-11e9-841a-50ce106b0776.png)

recontact with  Docusaurus Team to check this

**Comment by Keith-CY** [comment]
The response from algolia says that the version's contents are massive and really closed between them, the crawler only catches the master and latest one now for reducing waste of resources in the community projects.

**Comment by Keith-CY** [comment]
@zhouyun-zoe @kaikai1024 any idea?

**Comment by kaikai1024** [comment]
> the master and latest one 

Does it mean the `develop` version(next) and `latest released version`(v0.24)?

**Comment by Keith-CY** [comment]
> > the master and latest one
> 
> Does it mean the `develop` version(next) and `latest released version`(v0.24)?

Yep

**Comment by QingYanL** [comment]
已修复
