### ISSUE TITLE
Wrong display of `getting-started`.

### ISSUE THREAD

**Issue by kaikai1024** [citahub/citahub-docs#209]
https://docs.citahub.com/zh-CN/next/cita/getting-started#%E9%85%8D%E7%BD%AE%E8%8A%82%E7%82%B9

![Screenshot from 2019-05-06 10-29-03](https://user-images.githubusercontent.com/8768261/57204353-d9951500-6fe9-11e9-8f51-250149b10d15.png)

**Comment by zhouyun-zoe** [comment]
#214
