### ISSUE TITLE
wrong  title display in system/node

### ISSUE THREAD

**Issue by boundless-forest** [citahub/citahub-docs#239]
![选区_075](https://user-images.githubusercontent.com/11801722/57675485-bfe07700-7654-11e9-9f08-ab0cb2f4ab4b.png)

**Comment by zhouyun-zoe** [comment]
这里好奇怪，我昨天就看到这里有问题，然后改掉了，结果到网站上还是显示有问题。

**Comment by zhouyun-zoe** [comment]
而且我看不出源码的问题！

**Comment by zhouyun-zoe** [comment]
@wuyuyue

**Comment by leeyr338** [comment]
![屏幕快照 2019-05-14 下午2 50 15](https://user-images.githubusercontent.com/38514341/57676679-a5f46380-7657-11e9-8086-985cbe09b81f.png)

这是直接在 github 上打开源码的结果，显示是正确的。
有可能是 translated 后的结果出错了。check 一下。

**Comment by QingYanL** [comment]
已修复
