### ISSUE TITLE
有个问题是 `DOCUSAURUS_CODE_TABS` 下右边显示大纲无法自动跳转

### ISSUE THREAD

**Issue by kaikai1024** [citahub/citahub-docs#247]
有个问题是 `DOCUSAURUS_CODE_TABS` 下右边显示大纲无法自动跳转

_Originally posted by @kaikai1024 in https://github.com/cryptape/citahub-docs/pull/246/review_comment/create_

**Comment by QingYanL** [comment]
已修复
