### ISSUE TITLE
能不能把左边侧栏设置成默认折叠状态

### ISSUE THREAD

**Issue by kaikai1024** [citahub/citahub-docs#249]
![选区_002](https://user-images.githubusercontent.com/11801722/57899774-e12da700-7890-11e9-8172-ec145d3c759a.png)

有个建议: 能不能把左边侧栏设置成默认折叠状态.也就是说具体的合约接口, 在我打开文档的时候处于折叠状态

@zhouyun-zoe  这个框架可以做到吗

_Originally posted by @ouwenkg in https://github.com/cryptape/citahub-docs/pull/248#issuecomment-493299270_

**Comment by zhouyun-zoe** [comment]
二级目录默认折叠

**Comment by wuyuyue** [comment]
折叠框架不支持，这个不好改， 得深入hack的

**Comment by zhouyun-zoe** [comment]
@Keith-CY 巨巨有时间帮忙看下么

**Comment by zhouyun-zoe** [comment]
> 折叠框架不支持，这个不好改， 得深入hack的

@Keith-CY 巨巨有时间帮忙看下么

**Comment by Keith-CY** [comment]
这个修改需要 hack 框架, 如果性价比不高的话不建议修改

**Comment by kaikai1024** [comment]
暂时不改吧。 @zhouyun-zoe 
我觉得可以把  cita 下面的一些二级目录提到一级目录。比如 rpc 等

**Comment by zhouyun-zoe** [comment]
> 这个修改需要 hack 框架, 如果性价比不高的话不建议修改

这个比较刚需，反馈的人比较多，hack起来麻烦吗？

**Comment by Keith-CY** [comment]
> > 这个修改需要 hack 框架, 如果性价比不高的话不建议修改
> 
> 这个比较刚需，反馈的人比较多，hack起来麻烦吗？

也算不上麻烦, 只是添加 hack 得比较了解框架, 否则会出现意外的修改

**Comment by zhouyun-zoe** [comment]
> > > 这个修改需要 hack 框架, 如果性价比不高的话不建议修改
> > 
> > 
> > 这个比较刚需，反馈的人比较多，hack起来麻烦吗？
> 
> 也算不上麻烦, 只是添加 hack 得比较了解框架, 否则会出现意外的修改

从了解到实现麻烦不？如果有时间，最好能实现，现在看起来实在是眼花

**Comment by Keith-CY** [comment]
> > > > 这个修改需要 hack 框架, 如果性价比不高的话不建议修改
> > > 
> > > 
> > > 这个比较刚需，反馈的人比较多，hack起来麻烦吗？
> > 
> > 
> > 也算不上麻烦, 只是添加 hack 得比较了解框架, 否则会出现意外的修改
> 
> 从了解到实现麻烦不？如果有时间，最好能实现，现在看起来实在是眼花

实现的话一天内就能弄好, 但是要保证不对其他地方有影响可能得看下源码, 大约 3,4 天?

**Comment by leeyr338** [comment]
强烈建议搞一下，现在我们的文档体验真的很不好。
![屏幕快照 2019-05-24 上午10 03 14](https://user-images.githubusercontent.com/38514341/58297721-51957480-7e0b-11e9-9efd-7252e18f4f69.png)

**Comment by kaikai1024** [comment]
对， 还一个问题是 二三级标题不好区分

**Comment by zhouyun-zoe** [comment]
> > > > > 这个修改需要 hack 框架, 如果性价比不高的话不建议修改
> > > > 
> > > > 
> > > > 这个比较刚需，反馈的人比较多，hack起来麻烦吗？
> > > 
> > > 
> > > 也算不上麻烦, 只是添加 hack 得比较了解框架, 否则会出现意外的修改
> > 
> > 
> > 从了解到实现麻烦不？如果有时间，最好能实现，现在看起来实在是眼花
> 
> 实现的话一天内就能弄好, 但是要保证不对其他地方有影响可能得看下源码, 大约 3,4 天?

最近有时间的话可以帮忙改下吗？这里反馈的问题确实很多

**Comment by wuyuyue** [comment]
#317
