### ISSUE TITLE
The Title should be Chinese. How to do this? @zhouyun-zoe

### ISSUE THREAD

**Issue by kaikai1024** [citahub/citahub-docs#257]
The Title should be Chinese. How to do this? @zhouyun-zoe

_Originally posted by @kaikai1024 in https://github.com/cryptape/citahub-docs/pull/256#issuecomment-493388795_

**Comment by zhouyun-zoe** [comment]
需要去翻译平台上改，https://crowdin.com/project/citahub-docs。

**Comment by kaikai1024** [comment]
ok
