### ISSUE TITLE
目录调整

### ISSUE THREAD

**Issue by zhouyun-zoe** [citahub/citahub-docs#263]
1. 字体调整
   * 一级目录：黑色粗体 20px #000
   * 二级目录：黑色细体 16px #000
   * 三级目录：灰色细体 14px #717171

2. 显示调整
   * 一级二级目录均默认折叠
   * 只把当前阅读的文档sidebar字体显示加深，（现在是读过的就加深，看起来很乱）

**Comment by wuyuyue** [comment]
颜色字体可以全局css设置，折叠框架不支持调整。
建议深浅色找设计调整下，给个颜色

**Comment by zhouyun-zoe** [comment]
> 颜色字体可以全局css设置，折叠框架不支持调整。
> 建议深浅色找设计调整下，给个颜色

颜色不用变，就用现在默认的黑色和灰色就可以。

**Comment by zhouyun-zoe** [comment]
<img width="238" alt="image" src="https://user-images.githubusercontent.com/36949326/58525093-fc87a300-81fc-11e9-8099-228be110e3e5.png">

@wuyuyue 还是由如下问题：
1）`关于 CITA` 和` CITA 部署指南`作为二级目录，当前显示成了和三级目录一样的灰色，应该是黑色
2) 三级目录颜色不一致，当前一块黑色，一块灰色，应该统一成灰色
3）一级目录是20px+550？当前weight感觉和二级目录一，和昨天本地看的不太一致

**Comment by wuyuyue** [comment]
#317

**Comment by kaikai1024** [comment]
:clap: :clap: :clap:
