### ISSUE TITLE
`write-translations` 无法摘取一级目录的string

### ISSUE THREAD

**Issue by zhouyun-zoe** [citahub/citahub-docs#268]
<img width="258" alt="image" src="https://user-images.githubusercontent.com/36949326/58089111-9f855f00-7bf6-11e9-8035-70df97181713.png">

crowdin上找不到这几个string，没办法翻译

**Comment by wuyuyue** [comment]
@Keith-CY would you please describe  you hack solution before on this problem?

**Comment by Keith-CY** [comment]
![image](https://user-images.githubusercontent.com/7271329/58091948-7f0cd300-7bfd-11e9-9af9-6f4de3ac3765.png)
We can add labels of subcategories in the `website/data/load-sidebar.js`, then run the command `yarn run write-translations` to inject them into the `en.json` for uploading to crowdin.

**Comment by zhouyun-zoe** [comment]
@kaikai1024 , 等明天重构完文档，周五我统一把这里改过来。

**Comment by kaikai1024** [comment]
ok
