### ISSUE TITLE
文档中存在在2个ruby SDK 

### ISSUE THREAD

**Issue by jiangxianliang007** [citahub/citahub-docs#276]
![image](https://user-images.githubusercontent.com/24754263/58148121-086ce580-7c90-11e9-9d5c-0cdf352b009f.png)

**Comment by leeyr338** [comment]
这是 v0.24.0 的 docs 吗？
为什么我这里显示的是：
![屏幕快照 2019-05-22 下午5 30 00](https://user-images.githubusercontent.com/38514341/58163841-45000780-7cb7-11e9-9e6c-bb1810873450.png)

**Comment by kaikai1024** [comment]
next 版本有问题
