### ISSUE TITLE
网站现有有误，编译问题？

### ISSUE THREAD

**Issue by zhouyun-zoe** [citahub/citahub-docs#309]
![image](https://user-images.githubusercontent.com/36949326/58626308-131a2100-8307-11e9-85bf-c8d76161be7e.png)
https://docs.citahub.com/zh-CN/next/cita/getting-started/setup

源码没发现有什么问题

**Comment by Keith-CY** [comment]
![image](https://user-images.githubusercontent.com/7271329/58632105-4d8bba00-8317-11e9-9e68-a9a80ee91482.png)

是翻译的结果缺少了 `>` 符号

![image](https://user-images.githubusercontent.com/7271329/58632145-66946b00-8317-11e9-9327-6a8db08032f8.png)

最简单的解决方法是在翻译平台上吧 `>` 补上, 不过还是不建议嵌套太多 markdown 格式

**Comment by wuyuyue** [comment]
@leeyr338 @kaikai1024 , 问题在这里追踪；
上周跟CY一起定位过，不是框架本身的问题；可以看到无多语言版本是正常显示的
![image](https://user-images.githubusercontent.com/40381396/59337460-3bf0dc00-8d33-11e9-9641-945f8e8f260c.png)

目前可以定位的是翻译平台crowdin的问题，对于markdown的blockquote嵌套shell会出现符号丢失的问题; 

翻译前的markdown
![image](https://user-images.githubusercontent.com/40381396/59341356-482c6780-8d3a-11e9-91bc-05ae79e5347e.png)

翻译后的markdown
![image](https://user-images.githubusercontent.com/40381396/59341436-6abe8080-8d3a-11e9-9875-295938cad98f.png)

目前先建议文档里不要嵌套复杂markdown语法

**Comment by kaikai1024** [comment]
> 目前先建议文档里不要嵌套复杂markdown语法

ok， 我看看先把嵌套的语法重新组织一下，尽量避免
@zhouyun-zoe

**Comment by QingYanL** [comment]
已修复
