### ISSUE TITLE
Question: purpose of two directories

### ISSUE THREAD

**Issue by chaoticlonghair** [citahub/citahub-docs#32]
- [`/-US`] is it a typo?
- [`/en`] the files in this directory is less than others ([`/en-US`] or [`/zh-CN`]), is it a mistake?

[`/-US`]: https://github.com/cryptape/citahub-docs/tree/2121d5a71f0311d5ae077afbc71f614901025c60/-US
[`/en`]: https://github.com/cryptape/citahub-docs/tree/2121d5a71f0311d5ae077afbc71f614901025c60/en
[`/en-US`]: https://github.com/cryptape/citahub-docs/tree/2121d5a71f0311d5ae077afbc71f614901025c60/en-US
[`/zh-CN`]: https://github.com/cryptape/citahub-docs/tree/2121d5a71f0311d5ae077afbc71f614901025c60/zh-CN

**Comment by Keith-CY** [comment]
temp files that will be cleaned once project ready, also git history will be cleaned to shrink this repo

**Comment by Keith-CY** [comment]
and build dir will be ignored in repo

**Comment by Keith-CY** [comment]
> * [`/-US`](https://github.com/cryptape/citahub-docs/tree/2121d5a71f0311d5ae077afbc71f614901025c60/-US) is it a typo?
> * [`/en`](https://github.com/cryptape/citahub-docs/tree/2121d5a71f0311d5ae077afbc71f614901025c60/en) the files in this directory is less than others ([`/en-US`](https://github.com/cryptape/citahub-docs/tree/2121d5a71f0311d5ae077afbc71f614901025c60/en-US) or [`/zh-CN`](https://github.com/cryptape/citahub-docs/tree/2121d5a71f0311d5ae077afbc71f614901025c60/zh-CN)), is it a mistake?

This is a bug from crowdin, it take english as default language and some mistakes happen if not

**Comment by chaoticlonghair** [comment]
> This is a bug from crowdin

:dizzy_face:
