### ISSUE TITLE
快速入门/环境准备：网页显示不正确

### ISSUE THREAD

**Issue by leeyr338** [citahub/citahub-docs#320]
网页显示：
![屏幕快照 2019-06-11 下午5 19 48](https://user-images.githubusercontent.com/38514341/59259884-2a450100-8c6d-11e9-89f2-836b7cc544df.png)

github 显示：
![屏幕快照 2019-06-11 下午5 21 36](https://user-images.githubusercontent.com/38514341/59260012-69735200-8c6d-11e9-9ac5-93f1fc184eb9.png)

**Comment by wuyuyue** [comment]
#
Duplicate of #309 , let's track it in 309, I will close it first
