### ISSUE TITLE
> 目前先建议文档里不要嵌套复杂markdown语法

### ISSUE THREAD

**Issue by kaikai1024** [citahub/citahub-docs#321]
> 目前先建议文档里不要嵌套复杂markdown语法

ok， 我看看先把嵌套的语法重新组织一下，尽量避免
@zhouyun-zoe

_Originally posted by @kaikai1024 in https://github.com/cryptape/citahub-docs/issues/309#issuecomment-501204723_

**Comment by QingYanL** [comment]
已修复
