### ISSUE TITLE
Switch to Algolia Plan

### ISSUE THREAD

**Issue by Keith-CY** [citahub/citahub-docs#325]
As mentioned in a recent email from algolia team, our project is regarded as a commercial one, and required to switch to the starter or pro plan.

https://www.algolia.com/pricing/

**Comment by kaikai1024** [comment]
Does it have effect, like can not use the search, or something else.

**Comment by Keith-CY** [comment]
I'll ask for more information.

**Comment by wuyuyue** [comment]
it is recoverd now, only support latest(v0.25 now) and next version search. maybe we should update, if still have problem in next version. @kaikai1024

**Comment by kaikai1024** [comment]
@nanmuxiusi Would you help to connect algolia about this?

**Comment by nanmuxiusi** [comment]
> @nanmuxiusi Would you help to connect algolia about this?
OK
