### ISSUE TITLE
错误的引用“链接配置”？

### ISSUE THREAD

**Issue by blankwu** [citahub/citahub-docs#340]
链接配置 or 链级配置？

https://github.com/cryptape/citahub-docs/search?p=1&q=%E9%93%BE%E6%8E%A5%E9%85%8D%E7%BD%AE&unscoped_q=%E9%93%BE%E6%8E%A5%E9%85%8D%E7%BD%AE

**Comment by kaikai1024** [comment]
`链级配置`  :heavy_check_mark:

**Comment by nanmuxiusi** [comment]
> 链接配置 or 链级配置？
> 
> https://github.com/cryptape/citahub-docs/search?p=1&q=%E9%93%BE%E6%8E%A5%E9%85%8D%E7%BD%AE&unscoped_q=%E9%93%BE%E6%8E%A5%E9%85%8D%E7%BD%AE

Modified，thx

**Comment by QingYanL** [comment]
已修复
