### ISSUE TITLE
Something wrong with translation.

### ISSUE THREAD

**Issue by kaikai1024** [citahub/citahub-docs#35]
![screenshot from 2019-02-01 14-44-07](https://user-images.githubusercontent.com/8768261/52107076-f65b2e80-262f-11e9-8293-6cf588d8ff60.png)

* `emergency-brake.md` and `emg-brake.md`
* `amend.md` and `data-amend.md`

**Comment by Keith-CY** [comment]
I renamed amend to data-amend, emergency-brake to emg-brake for some unknown problem from docusaurus. Will it matters? Use previous name if necessary.

**Comment by kaikai1024** [comment]
> I renamed amend to data-amend, emergency-brake to emg-brake for some unknown problem from docusaurus. Will it matters? Use previous name if necessary.

You should rename all the files. cause i can't opent these two links in Chinese version. I think the name is the reason 

http://docs.citahub.com/zh-CN/next/cita/system/amend

http://docs.citahub.com/zh-CN/next/cita/system/emergency-brake

**Comment by Keith-CY** [comment]
Cause it's not determined source code stay in cita or in citahub-docs, I didn't change source docs.

**Comment by Keith-CY** [comment]
- emergency-brake => emg-brake
- amend => data-amend
- role-management => role-mng
- group-management => group-mng
- emergency-brake => emg-brake
- components => comp
- consensus => cons
- reference/addresses => ref/addresses

These are the docs renamed
