### ISSUE TITLE
Fix the link of `version-1.0.0`

### ISSUE THREAD

**Issue by kaikai1024** [citahub/citahub-docs#380]
https://docs.citahub.com/zh-CN/cita/advanced-use/contracts/solidity#%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C

![2019-09-26-153113_380x240_scrot](https://user-images.githubusercontent.com/8768261/65667685-c9ea9b80-e072-11e9-8ac4-b3dbd15da972.png)

**Comment by QingYanL** [comment]
已修复
