### ISSUE TITLE
link errors

### ISSUE THREAD

**Issue by boundless-forest** [citahub/citahub-docs#389]
1. https://docs.citahub.com/zh-CN/contributing
【getting_started】跳转不对
![Selection_006](https://user-images.githubusercontent.com/11801722/68364438-e517f300-0168-11ea-8bdb-e05ac5a1a71b.png)

2. https://docs.citahub.com/zh-CN/cita/node/cons-node
 【setStake 接口】404
![Selection_007](https://user-images.githubusercontent.com/11801722/68365410-8acc6180-016b-11ea-8065-c3d318e177c2.png)

**Comment by QingYanL** [comment]
已修复
