### ISSUE TITLE
Add "Upgrade considerations" from operation's advice

### ISSUE THREAD

**Issue by zengbing15** [citahub/citahub-docs#53]
https://docs.citahub.com/zh-CN/next/cita/configuration/chain-config#enable-tls-%E6%98%AF%E5%90%A6%E5%BC%80%E9%80%9A%E8%8A%82%E7%82%B9%E9%97%B4%E9%80%9A%E8%AE%AF%E5%8A%A0%E5%AF%86

**Comment by kaikai1024** [comment]
yeah, It's better to have Upgrade considerations about versions.

Btw, Already have [protocol-upgrade](https://docs.citahub.com/en-US/cita/protocol-upgrade/overview) doc
