### ISSUE TITLE
fix typo about upper and lower case letters  

### ISSUE THREAD

**Issue by zengbing15** [citahub/citahub-docs#57]

**Comment by zhouyun-zoe** [comment]
More details is needed 😄. Like, which docs?

**Comment by kaikai1024** [comment]
This one? #59

**Comment by zengbing15** [comment]
![image](https://user-images.githubusercontent.com/40650475/53713664-9b169900-3e86-11e9-8f20-7b5afb055d3b.png)
ReBirth
