### ISSUE TITLE
`getting_start` part of CITA should use released version first

### ISSUE THREAD

**Issue by kaikai1024** [citahub/citahub-docs#60]
-------Chinese------

这个部分应该把 发布版本的使用优先放到前面，编译源码靠后是一个可选项

**Comment by zhouyun-zoe** [comment]
https://facebook.github.io/react-native/docs/getting-started
找个是我目前看到的一个比较理想的 getting-started 文档，找个网站用的和我们相同的框架，前端渲染是一样的。

我们也可以用这种格式：系统，部署方式的组合。和 #102 一起考虑。
![image](https://user-images.githubusercontent.com/36949326/55300949-b61bff00-546c-11e9-9e93-80e52a1a798d.png)
