### ISSUE TITLE
Auto-build for new version

### ISSUE THREAD

**Issue by zhouyun-zoe** [citahub/citahub-docs#67]

**Comment by zhouyun-zoe** [comment]
Please notice: this issue should be fixed with **High Priority**!

**Comment by jiangxianliang007** [comment]
随CITA 版本发布自动部署最新版本，这块有问题，CI部署是从master分支pull 代码 编译后 push到docs repo 的 gh-pages 分支，然后要把本地生成的新版本文档 再push 到 master 分支（master 分支有保护不能直接push)， 是不是要push 到 其他分支 再去调用 github 的api 自动提交PR， review 后才发布，这种流程是做不到自动化发布CITA release 最新版本文档了。 review PR 就要人工介入了，@wuyuyue 有其他办法吗?

**Comment by wuyuyue** [comment]
step example with 0.23
```
yarn run version 0.23
yarn run write-translations
cd ..
yarn run crowdin:upload
yarn run crowdin:download
git add --all
git commit -m "feat: init new version cita docs"
git push origin v0.23:v0.23

```

最后通过v0.23手工PR merge到master

clese this issue first, if any problem , reopen new one
