### ISSUE TITLE
CITA 文档重构：新的目录，更多的内容

### ISSUE THREAD

**Issue by zhouyun-zoe** [citahub/citahub-docs#78]
- 欢迎
- CITA
    - [ ] 概述 overview（协议+结构描述）
    - [x] 快速入门
        - 环境准备 setup (release-secp256k1 & docker)
        - getting-startted
        - basic usage

    - [x] 配置说明
        - 链级配置
        - 微服务配置

    - [x] 部署说明
        - 发布包介绍
        - 本机 - 同一个容器
        - docker compose
        - 分布式部署
        - 云

    - [x] 命令说明
        - 启动节点
        - 停止节点
        - ping
        - top
        - ...

    - [x] 节点管理
        - [x] 节点分类
            - 共识节点
            - 非共识节点
        - [x] 增删节点
            - 增删普通节点（白名单）
            - 增删共识节点（系统合约）

    - [x] 用户与权限管理（系统合约）
        - 账户系统
            - 账户系统使用示例
        - 权限系统
            - 权限系统使用示例
        - 权限系统插件

    - [x] 数据隐私及安全
        - [x] 概述
        - [x] zktx
        - [x] 侧链

    - [x] 经济模型选择
        - [x] 基础设置
            * block quota limit
            * account quota limit
        - [x]  两种模型
            * Quota 模型
            * Charge 模型
                * 设置 QuotaPrice
                * 设置 Fee back

    - [x] 系统治理
        - 紧急制动
        - 数据订正

    - [x] 数据备份与恢复
        - 概述
        - 全数据拷贝
        - 节点快照

    - [x] 升级说明
        - [x] 概述
        - [x] 版本升级
        - [x] 协议升级
            - overview
            - Operation
            - 已有协议
                - v0
                - v1

    - [x] 存证

    - [x] Hacking
        - [x] 源码编译
        - [x] 日志管理
        - [x] 自动执行
        - [x] 链上治理
        - [x] 智能合约
            * Solidity 合约编写，编译，部署，调用
            * Rust 原生合约编写，部署，调用
            * 合约的批量调用

    - [x] 架构设计
        * 微服务架构
        * 交易
        * 共识

    - [x] rpc 指南
        * 类型
        * 列表
        * 错误类型
    - [x] 系统合约接口指南
        * 接口
        * 错误类型
    - [x] 系统保留地址
    - [x] FAQ

- 工具链
- 贡献代码

**Comment by zhouyun-zoe** [comment]
首页提一下软件协议

**Comment by zhouyun-zoe** [comment]
再加一个大模块：数据隐私与安全

**Comment by zhouyun-zoe** [comment]
工具指南里面加上：运维工具

**Comment by zhouyun-zoe** [comment]
用户管理注明：目前没用 CA，并给出一些详细的指南。

**Comment by zhouyun-zoe** [comment]
@zhouyun-zoe 负责写`经济模型`部分

**Comment by kaikai1024** [comment]
> 系统运维

这个是不是不太好？文档大部分是 系统运维？

**Comment by zhouyun-zoe** [comment]
> > 系统运维
> 
> 这个是不是不太好？文档大部分是 系统运维？
- 或者其他的名字？这一块我觉得是使用+运维
- 或者站在开发者的角度还需要哪些文档？这一块客户问题反馈的比较多，所以想尽可能写的详细点。

**Comment by kaikai1024** [comment]
~~系统运维感觉是给运维人员看的，就 `系统` 吧~~

**Comment by kaikai1024** [comment]
@kaikai1024 用户和权限系统

**Comment by boundless-forest** [comment]
@ouwenkg 协议升级

**Comment by boundless-forest** [comment]
@ouwenkg 特殊治理

**Comment by kaikai1024** [comment]
@kaikai1024 智能合约

**Comment by ouwenkg** [comment]
@ouwen

**Comment by boundless-forest** [comment]
@ouwenkg rpc 指南

**Comment by zhouyun-zoe** [comment]
@zhouyun-zoe 数据备份与恢复，版本升级

**Comment by leeyr338** [comment]
OK, 我明天先写快速入门这部份。

**Comment by leeyr338** [comment]
先写文档内容，`sidebar.json` 后面统一改?
然后每个一级目录占一个文件夹？

**Comment by kaikai1024** [comment]
> 先写文档内容，sidebar.json 后面统一改?

写的时候就把相关部分的 sidebar 改了，逐步重构，保证每次重构文档可用。可以参考之前的几次 PR

> 然后每个一级目录占一个文件夹？

恩

**Comment by boundless-forest** [comment]
@ouwenkg 配置说明

**Comment by kaikai1024** [comment]
> 我觉得可以把 cita 下面的一些二级目录提到一级目录。比如 rpc 等

**Comment by kaikai1024** [comment]
重构一级目录

一级目录太浪费了，只有四个

**Comment by kaikai1024** [comment]
二级目录如果无法折叠，可能要对二级目录做下整理

**Comment by boundless-forest** [comment]
> 二级目录如果无法折叠，可能要对二级目录做下整理

提议: 快速入门可以放在 welcome 里, 现在的 welcome 里只有文档概要一条, 占用一个一级目录, 很是浪费啊

**Comment by kaikai1024** [comment]
可以考虑 CITA 下的二级目录升级为 一级目录 @zhouyun-zoe

**Comment by kaikai1024** [comment]
目录暂时不做新的改动

**Comment by kaikai1024** [comment]
智能合约暂时拆开，用三级目录

**Comment by QingyangKong** [comment]
数据隐私部分可以加入 TEE 的相关信息吗？

**Comment by zhouyun-zoe** [comment]
> 数据隐私部分可以加入 TEE 的相关信息吗？

可以，我先在概述里面加上一段，后续我了解下之前项目的细节内容，再补充更多内容。

**Comment by kaikai1024** [comment]
@kaikai1024 Hacking 其他部分

**Comment by leeyr338** [comment]
~~@leeyr338 , 配置说明。~~

**Comment by leeyr338** [comment]
@leeyr338 , 存证。

**Comment by kaikai1024** [comment]
@kaikai1024 系统合约接口指南

**Comment by boundless-forest** [comment]
@ouwenkg 部署说明

**Comment by zhouyun-zoe** [comment]
@zhouyun-zoe 节点管理

**Comment by leeyr338** [comment]
@leeyr338 系统保留地址

**Comment by leeyr338** [comment]
@leeyr FAQ

**Comment by kaikai1024** [comment]
目录最后进行一次细节调整

**Comment by kaikai1024** [comment]
@kaikai1024 数据备份及恢复

**Comment by zhouyun-zoe** [comment]
> @kaikai1024 数据备份及恢复

这个我写了 @kaikai1024

**Comment by kaikai1024** [comment]
ok，麻烦尽快处理一下 PR

**Comment by leeyr338** [comment]
@leeyr338 命令说明

**Comment by kaikai1024** [comment]
概述等最后目录更新完成之后补充结构信息

**Comment by boundless-forest** [comment]
> ok，麻烦尽快处理一下 PR

I do this

**Comment by boundless-forest** [comment]
@ouweng 升级说明, 剩余部分
