### ISSUE TITLE
How can i find the citahub-docs repo link from the doc

### ISSUE THREAD

**Issue by kaikai1024** [citahub/citahub-docs#93]
I can not find it

**Comment by zhouyun-zoe** [comment]
Please help to add GitHub link in navi bar. @wuyuyue

**Comment by kaikai1024** [comment]
>  in navi bar.

where?

**Comment by zhouyun-zoe** [comment]
![image](https://user-images.githubusercontent.com/36949326/55300734-90dac100-546b-11e9-81bd-a556abbea7d4.png)
