### ISSUE TITLE
Set default language to Chinese

### ISSUE THREAD

**Issue by zhouyun-zoe** [citahub/citahub-docs#94]

**Comment by kaikai1024** [comment]
棒
我觉得现在文档最重要的是中文文档的**完美支持**，翻译及相关的的事情可以放放

**Comment by Keith-CY** [comment]
https://github.com/facebook/Docusaurus/issues/1332#issuecomment-479835208, just wait for docusaurus v2

**Comment by wuyuyue** [comment]
I think we could change the default url from 'en-US/welcome' to
window.location.href = 'zh-CN/welcome' in index.html as temporary solution first
https://github.com/cryptape/citahub-docs/pull/141
