### ISSUE TITLE
Can not open amend doc of Chinese version.

### ISSUE THREAD

**Issue by kaikai1024** [citahub/citahub-docs#96]
https://docs.citahub.com/zh-CN/cita/system/amend

**Comment by zhouyun-zoe** [comment]
Fix it in #105

**Comment by Keith-CY** [comment]
Is this issue fixed?

**Comment by kaikai1024** [comment]
seems ok

**Comment by zhouyun-zoe** [comment]
Still have problem!

**Comment by wuyuyue** [comment]
it is working now. there is some miss step in ci for fix #105 . could double-check and close this
